version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    restart: always
    image: mysql:5.7.19
    volumes:
      - ./compose/mysql/:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
    # for test
    ports:
      - "127.0.0.1:3307:3306"
      # (HOST:CONTAINER)
    env_file:
      - .env

  web:
    # restart: always
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    command: sh gunicorn.sh # ["/bin/bash", "gunicorn.sh"]
    ports:
      - "8080:8002"
      # (HOST:CONTAINER)
    volumes:
      - ./logs:/var/logs/
      - ./collect_static:/code/collect_static
      - ./static:/code/static
      - ./templates:/code/templates
      - ./uploads:/code/uploads
    env_file: .env
    depends_on:
      - redis
      - db

  nginx:
    restart: always
    image: nginx:1.13.0
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d/
      - ./staticfiles:/code/staticfiles
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      # (HOST:CONTAINER)
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    command: sh celery.sh
    volumes:
      - ./logs:/var/logs/
      - ./uploads:/code/uploads
    depends_on:
      - redis
      - db
    env_file: .env

  celery-beat:
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    command: sh celery-beat.sh
    volumes:
      - ./logs:/var/logs/
    depends_on:
      - redis
      - db
    env_file: .env